apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: coolstore-eap8-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: gitea-push
      bindings:
        - ref: coolstore-eap8-binding
      template:
        ref: coolstore-eap8-template
