apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: coolstore-eap8-pipeline
spec:
  params:
    - name: git-url
      type: string
      description: Git repository URL
      default: https://gitea-gitea.apps.cluster-jxznt.jxznt.sandbox3409.opentlc.com/user01/coolstore-eap7
    - name: git-revision
      type: string
      description: Git revision
      default: main
    - name: image-name
      type: string
      description: Container image name
      default: image-registry.openshift-image-registry.svc:5000/user01-dev/coolstore-eap8:latest
    - name: namespace
      type: string
      description: Target namespace
      default: user01-dev
  workspaces:
    - name: shared-workspace
      description: Workspace shared across tasks
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: maven-build
      taskRef:
        name: maven-build
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: apply-cli
      taskRef:
        name: apply-cli
      runAfter:
        - maven-build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-image
      taskRef:
        name: build-image
      runAfter:
        - apply-cli
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build-image
      params:
        - name: NAMESPACE
          value: $(params.namespace)
      workspaces:
        - name: source
          workspace: shared-workspace
